### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by PeterPo** [foo123/MOD3#2]
Hi,
Great library - I want to start using it in my project so just wondering if you can confirm that this library is using the same license as where it was ported from? (AS3MOD is licensed under MIT)

**Comment by foo123** [comment]
Hi there. seen the email also. i'm not sure this is needed. The MOD3 code is unlicensed although it explicitly states that it is a port of the AS3Mod library (plus some extra features which are added from time to time, like new 3d engines support, multi-thread-parallel code, new modifiers etc

if you ask me the code is unlicensed. What do you think is it necessary to add the license of the original code?

**Comment by foo123** [comment]
NOTE: there is a version of MOD3 in progress which fixes some issues with multi-threading and object-oriented structure of the code (it will be uploaded some time soon,due to other projects which have priority right now)

**Comment by PeterPo** [comment]
Hi! Many thanks for your answer! 
Leaving the code without a license makes people scared of using and contributing to the code since it is not entirely clear how they are allowed to use the library. 

I would very much appreciate if you could add the same license as the original author of the library (MIT) or the same as three.js for the additions you have made. Otherwise we can't consider this project to be a free open source project and people should be aware of this before contributing or using it.

Really looking forward to your future updates!

**Comment by foo123** [comment]
OK MIT license of the original code added (see updated readme).

Note that unlicense does not mean the code is not open  source or free. Just that absolutely no license is used (see public domain and unlicense for further details)

So if anyone should have a problem, that should be the author (e.g me) and not anyone else, since no speciifc license is there, no-one (else) is to blame.

Anyway, per the request, the MIT license is added.

**Comment by PeterPo** [comment]
Many thanks for clarifying that the code continues to be licensed under MIT!
