### ISSUE TITLE
Bend along another axis

### ISSUE THREAD

**Issue by JCengineer** [foo123/MOD3#3]
Hi foo123,

I'm having an issue because the domain that hold the docs for AS3dMod seem to have expired! I can't find out how to change the axis of bend for threejs. At the moment, it's only bending around the y (up) axis. Can you please let me know how to change it so it bends around z (towards screen) ?

I know it's not a code fault but it's a useability issue that I'm sure many others will come across. 
Thanks.
J

**Comment by foo123** [comment]
Hello, the bend modifier is a little awkward as implemented in AS3dmod (and ported to MOD3) as it does not speciffy an axis of rotation but rather the relative axis with respect to which one is longer or shorter and then an angle for this relatove axis and a constraint if bend is in both sides or in one side (LEFT or RIGHT) se the code for bend modifier here https://github.com/foo123/MOD3/blob/master/src/modifiers/Bend.js#L140

Yopu will see that one has to define a switchAxes flag in order to change axis. So it depends on the rewlative dimensions (along x,y,z) of the object you want to bend. Probably the bend modifier will be changed to reflect bending along independent axes, but this is the actual port at this time.

**NOTE**:  MOD3 will undergo a major refactor and update (which has started but not completed yet). The functionality and API interface is expected to stay the same for the most part however some API changes will be made for easier use. It is a matter if time for me to make all the changes, but keep it in mind

**Comment by JCengineer** [comment]
Ok, great to know. Thanks for the information. J
